# Generated by Django 6.0.5 on 2026-07-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=50, unique=True, verbose_name='Numéro du chèque')),
                ('matricule', models.CharField(max_length=50, verbose_name='Matricule du camion')),
                ('date_remise', models.DateField(verbose_name='Date de remise')),
                ('montant_initial', models.FloatField(verbose_name='Montant initial (MAD)')),
                ('montant_consomme', models.FloatField(default=0.0, verbose_name='Montant consommé')),
                ('solde_restant', models.FloatField(blank=True, null=True, verbose_name='Solde restant')),
                ('date_epuisement', models.DateField(blank=True, null=True, verbose_name="Date d'épuisement")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Chèque actif')),
            ],
        ),
    ]
